name: Run CodeQL

on:
  merge_group:
  pull_request:
    branches:
      - feature/*
      - main
  push:
    branches:
      - feature/*
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  code-ql:
    name: CodeQL
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - javascript-typescript
          - python
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Initialize CodeQL
        uses: github/codeql-action/init@4e94bd11f71e507f7f87df81788dff88d1dacbfb
        with:
          languages: ${{ matrix.language }}

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: 10
          run_install: false

      - name: Set up Node
        if: matrix.language == 'javascript-typescript'
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies for frontend
        if: matrix.language == 'javascript-typescript'
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@4e94bd11f71e507f7f87df81788dff88d1dacbfb
        with:
          category: /language:${{ matrix.language }}
